---
title: "HW 5"
author: "Haichen Liu"
date: "2015Äê10ÔÂ14ÈÕ"
output: html_document
---

```{r}
packages <- c("data.table", "jpeg")
sapply(packages, require, character.only = TRUE, quietly = TRUE)
```

```{r}
# Question 1: Match the data based on the country shortcode. How many of the IDs match? 
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
f <- file.path(getwd(), "GDP.csv")
download.file(fileURL, f)
dtGDP <- data.table(read.csv(f, skip = 4, nrows = 215))
dtGDP <- dtGDP[X != ""]
dtGDP <- dtGDP[, list(X, X.1, X.3, X.4)]
setnames(dtGDP, c("X", "X.1", "X.3", "X.4"), c("CountryCode", "rankingGDP", "Long.Name", "gdp"))
fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
f <- file.path(getwd(), "EDSTATS_Country.csv")
download.file(fileURL, f)
dtEd <- data.table(read.csv(f))
dt <- merge(dtGDP, dtEd, all = TRUE, by = c("CountryCode"))
sum(!is.na(unique(dt$rankingGDP)))
## 189 is the number of IDs that match in the data frame.
```

```{r}
# Question 2: Sort the data frame in descending order by GDP rank (so United States is last). What is the 13th country in the resulting data frame?
dt[order(rankingGDP, decreasing = FALSE), list(CountryCode, Long.Name.x, Long.Name.y, rankingGDP, gdp)][13]
## Spain is the 13th country in the data frame.
```

```{r}
# Question 3: What are the average GDP rankings for the "High income: OECD" and "High income: nonOECD" groups? 
dt[, mean(rankingGDP, na.rm = TRUE), by = Income.Group]
## 32.96667,91.91304 is the mean GDP ranking for the High income: OECD & nonOECD groups.
```

```{r}
# Question 4: Cut the GDP ranking into 5 separate quantile groups. Make a table versus Income.Group. How many countries are Lower middle income but among the 38 nations with highest GDP?
breaks <- quantile(dt$rankingGDP, probs = seq(0, 1, 0.2), na.rm = TRUE)
dt$quantileGDP <- cut(dt$rankingGDP, breaks = breaks)
dt[Income.Group == "Lower middle income", .N, by = c("Income.Group", "quantileGDP")]
## 5 is the number of countries in the Lower middle income group With one of the 38 highest GDP.
```
